### create user 
POST {{ BASE_URL }}/user
Content-Type: application/json
{
    "name": "Toko Bintang",
    "userName": "TokoBintang",
    "password": "1234",
    "confirmPassword": "1234",
    "role": "admin"
}

### login user
POST {{ BASE_URL }}/users/login
Content-Type: application/json
{
    "userName": "TokoBintang",
    "password": "1234"
}

{{ 
$global.accessToken = JSON.parse(responseBody).accessToken;
$global.refreshToken = JSON.parse(responseBody).refreshTokenToken;
 }}

 ### update user
 PUT {{ BASE_URL }}/users/1
Content-Type: application/json
Authorization: Bearer {{ $global.accessToken}}
{
    "name": "Toko Bintang",
    "userName": "TokoBintang",
    "password": "1234",
    "confirmPassword": "1234",
    "role": "admin"
}